version: '3.4'

services:
  cache:
    image: redis
    command: redis-server --requirepass testPassword

  sql.data:
    image: microsoft/mssql-server-linux:2017-latest

  rabbitmq:
    image: rabbitmq:3-management-alpine

  config:
    image: hyness/spring-cloud-config-server

  eurekareg:
    image: steeltoeoss/eurekaserver

  identity.api:
    image: eshop/identity.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile
    depends_on:
      - sql.data
      - eurekareg
      
  catalog.api:
    image: eshop/catalog.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile
    depends_on:
      - sql.data
      - eurekareg
      - rabbitmq 
      - cache 
      - config  

  basket.api:
    image: eshop/basket.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Basket/Basket.API/Dockerfile
    depends_on:
      - sql.data
      - eurekareg
      - rabbitmq
  web:
    image: eshop/web:${TAG:-latest}
    build:
      context: .
      dockerfile: src/UI/Web/Dockerfile
    depends_on:
      - sql.data
      - eurekareg
